from __future__ import annotations

import io
import sys
from typing import Any, List, Optional

from jcl_models import DDStatement, ExecStep, JobAST, to_model
from jcl_parser import build_ast, parse_jcl


def _parm_to_args(parm: Any) -> str:
    if isinstance(parm, list):
        return " ".join(str(p) for p in parm)
    return str(parm)


def _disp_label(disp: Any) -> str:
    if isinstance(disp, list):
        return f"({','.join(str(d) for d in disp)})"
    return str(disp)


def _dd_env_lines(dds: List[DDStatement], indent: str) -> List[str]:
    lines = []
    for dd in dds:
        dsn = dd.params.get("DSN") or f"<{dd.name}>"
        disp = dd.params.get("DISP")
        comment = f"  # DISP={_disp_label(disp)}" if disp else ""
        lines.append(f"{indent}    DD_{dd.name}: {dsn}{comment}")
    return lines


def _job_block(step: ExecStep, needs: Optional[List[str]]) -> List[str]:
    lines: List[str] = []
    lines.append(f"  {step.name}:")
    lines.append(f"    runs-on: ubuntu-latest")
    if needs:
        lines.append(f"    needs: [{', '.join(needs)}]")
    if step.dds:
        lines.append(f"    env:")
        lines.extend(_dd_env_lines(step.dds, indent="  "))
    lines.append(f"    steps:")
    lines.append(f"      - uses: actions/checkout@v4")
    pgm = step.params.get("PGM", "")
    parm = step.params.get("PARM")
    run_cmd = f"{pgm} {_parm_to_args(parm)}" if parm else pgm
    lines.append(f"      - name: Run {pgm}")
    lines.append(f"        run: {run_cmd}")
    return lines


def to_github_actions(model: JobAST) -> str:
    job_name = model.name or "JCL_JOB"
    buf = io.StringIO()

    buf.write(f"# Generated by jcl-parser from JOB {job_name}\n")
    buf.write(f"name: {job_name}\n")
    buf.write("on:\n")
    buf.write("  workflow_dispatch: {}\n")
    buf.write("\n")
    buf.write("jobs:\n")

    prev: List[str] = []
    for step in model.steps:
        buf.write("\n")
        needs = [prev[-1]] if prev else None
        for line in _job_block(step, needs):
            buf.write(line + "\n")
        prev.append(step.name)

    return buf.getvalue()


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python jcl_to_gha.py <jcl-file>")
        return 1

    with open(sys.argv[1], encoding="utf-8") as handle:
        statements = parse_jcl(handle.readlines())

    model = to_model(build_ast(statements))
    print(to_github_actions(model), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
