from __future__ import annotations

import io
import sys
from typing import Any, Callable, List, Optional

from jcl_file_ops import DDFileOp, plan_step_file_ops
from jcl_dsn_path import DEFAULT_BASE_DIR
from jcl_models import ExecStep, JobAST, to_model
from jcl_parser import build_ast, parse_jcl


def _parm_to_args(parm: Any) -> str:
    if isinstance(parm, list):
        return " ".join(str(p) for p in parm)
    return str(parm)


def _disp_label(op: DDFileOp) -> str:
    parts = [p for p in (op.disp_status, op.disp_normal, op.disp_abnormal) if p]
    if len(parts) > 1:
        return f"({','.join(parts)})"
    return parts[0] if parts else ""


def _dd_env_lines(ops: List[DDFileOp], indent: str) -> List[str]:
    lines = []
    for op in ops:
        disp = _disp_label(op)
        comment = f"  # DISP={disp}" if disp else ""
        lines.append(f"{indent}    DD_{op.dd_name}: {op.path}{comment}")
    return lines


def _file_op_step(name: str, ops: List[DDFileOp], select: Callable[[DDFileOp], List[str]]) -> List[str]:
    commands = [cmd for op in ops for cmd in select(op)]
    if not commands:
        return []
    lines = [f"      - name: {name}", "        run: |"]
    lines.extend(f"          {cmd}" for cmd in commands)
    return lines


def _job_block(step: ExecStep, needs: Optional[List[str]], base_dir: str) -> List[str]:
    ops = plan_step_file_ops(step, base_dir)

    lines: List[str] = []
    lines.append(f"  {step.name}:")
    lines.append(f"    runs-on: ubuntu-latest")
    if needs:
        lines.append(f"    needs: [{', '.join(needs)}]")
    if ops:
        lines.append(f"    env:")
        lines.extend(_dd_env_lines(ops, indent="  "))
    lines.append(f"    steps:")
    lines.append(f"      - uses: actions/checkout@v4")
    lines.extend(_file_op_step("Prepare datasets", ops, lambda op: op.pre_ops))

    pgm = step.params.get("PGM", "")
    parm = step.params.get("PARM")
    run_cmd = f"{pgm} {_parm_to_args(parm)}" if parm else pgm
    lines.append(f"      - name: Run {pgm}")
    lines.append(f"        run: {run_cmd}")

    lines.extend(_file_op_step("Finalize datasets", ops, lambda op: op.post_ops))
    return lines


def to_github_actions(model: JobAST, base_dir: str = DEFAULT_BASE_DIR) -> str:
    job_name = model.name or "JCL_JOB"
    buf = io.StringIO()

    buf.write(f"# Generated by jcl-parser from JOB {job_name}\n")
    buf.write(f"name: {job_name}\n")
    buf.write("on:\n")
    buf.write("  workflow_dispatch: {}\n")
    buf.write("\n")
    buf.write("jobs:\n")

    prev: List[str] = []
    for step in model.steps:
        buf.write("\n")
        needs = [prev[-1]] if prev else None
        for line in _job_block(step, needs, base_dir):
            buf.write(line + "\n")
        prev.append(step.name)

    return buf.getvalue()


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python jcl_to_gha.py <jcl-file>")
        return 1

    with open(sys.argv[1], encoding="utf-8") as handle:
        statements = parse_jcl(handle.readlines())

    model = to_model(build_ast(statements))
    print(to_github_actions(model), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
